<?php

declare(strict_types=1);

namespace App\DTOs\Settings;

final readonly class SettingsUpdateDto
{
    public function __construct(
        // Hero
        public ?string $hero_title_line_1 = null,
        public ?string $hero_title_line_2 = null,
        public ?string $hero_title_line_3 = null,
        public ?string $hero_eyebrow = null,
        public ?string $hero_button_text = null,
        public ?string $hero_use_spline = null,
        public ?string $hero_background = null,
        public ?string $hero_media = null,
        // Sections
        public ?string $agents_title = null,
        public ?string $agents_subtitle = null,
        public ?string $cases_title = null,
        public ?string $cases_subtitle = null,
        public ?string $process_title = null,
        public ?string $process_subtitle = null,
        public ?string $blog_title = null,
        public ?string $blog_subtitle = null,
        // Partners
        public ?string $partners_pill = null,
        public ?string $partners_title = null,
        public ?string $partners_subtitle = null,
        public ?string $partner_variant1_badge = null,
        public ?string $partner_variant1_title = null,
        public ?string $partner_variant1_desc = null,
        public ?string $partner_variant1_percent = null,
        public ?string $partner_variant1_percent_label = null,
        public ?string $partner_variant1_amount_label = null,
        public ?string $partner_variant1_amount_value = null,
        public ?string $partner_variant1_tags = null,
        public ?string $partner_variant2_badge = null,
        public ?string $partner_variant2_title = null,
        public ?string $partner_variant2_desc = null,
        public ?string $partner_variant2_percent = null,
        public ?string $partner_variant2_percent_label = null,
        public ?string $partner_variant2_amount_label = null,
        public ?string $partner_variant2_amount_value = null,
        public ?string $partner_variant2_tags = null,
        public ?string $partner_earn_min_label = null,
        public ?string $partner_earn_min_value = null,
        public ?string $partner_earn_min_note = null,
        public ?string $partner_earn_top_label = null,
        public ?string $partner_earn_top_value = null,
        public ?string $partner_earn_top_note = null,
        public ?string $partner_earn_audit_label = null,
        public ?string $partner_earn_audit_value = null,
        public ?string $partner_earn_audit_note = null,
        public ?string $partner_steps_title = null,
        public ?string $partner_step1_num = null,
        public ?string $partner_step1_title = null,
        public ?string $partner_step1_desc = null,
        public ?string $partner_step2_num = null,
        public ?string $partner_step2_title = null,
        public ?string $partner_step2_desc = null,
        public ?string $partner_step3_num = null,
        public ?string $partner_step3_title = null,
        public ?string $partner_step3_desc = null,
        public ?string $partner_step4_num = null,
        public ?string $partner_step4_title = null,
        public ?string $partner_step4_desc = null,
        public ?string $partner_why_title = null,
        public ?string $partner_why1_title = null,
        public ?string $partner_why1_desc = null,
        public ?string $partner_why2_title = null,
        public ?string $partner_why2_desc = null,
        public ?string $partner_why3_title = null,
        public ?string $partner_why3_desc = null,
        public ?string $partner_why4_title = null,
        public ?string $partner_why4_desc = null,
        public ?string $partners_cta_label = null,
        public ?string $partners_cta_title = null,
        public ?string $partners_cta_desc = null,
        public ?string $partners_cta_button = null,
        // CTA
        public ?string $cta_pill = null,
        public ?string $cta_title = null,
        public ?string $cta_subtitle = null,
        public ?string $cta_button_text = null,
        public ?string $cta_button_telegram = null,
        public ?string $cta_note = null,
        // Contact Form
        public ?string $contact_form_pill = null,
        public ?string $contact_form_title = null,
        public ?string $contact_form_subtitle = null,
        public ?string $contact_form_name_label = null,
        public ?string $contact_form_phone_label = null,
        public ?string $contact_form_company_label = null,
        public ?string $contact_form_submit_text = null,
        public ?string $contact_form_success_title = null,
        public ?string $contact_form_success_message = null,
        public ?string $contact_form_privacy_note = null,
        // Contacts
        public ?string $contact_phone = null,
        public ?string $contact_email = null,
        public ?string $contact_address = null,
        // Footer
        public ?string $footer_brand_name = null,
        public ?string $footer_brand_desc = null,
        public ?string $footer_products_title = null,
        public ?string $footer_company_title = null,
        public ?string $footer_contacts_title = null,
        public ?string $footer_phone = null,
        public ?string $footer_email = null,
        public ?string $footer_telegram = null,
        public ?string $footer_copyright = null,
        // Marquee
        public ?string $marquee_items = null,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(...$data);
    }

    public function toArray(): array
    {
        return array_filter([
            'hero_title_line_1' => $this->hero_title_line_1,
            'hero_title_line_2' => $this->hero_title_line_2,
            'hero_title_line_3' => $this->hero_title_line_3,
            'hero_eyebrow' => $this->hero_eyebrow,
            'hero_button_text' => $this->hero_button_text,
            'hero_use_spline' => $this->hero_use_spline === 'true' ? 'true' : 'false',
            'hero_background' => $this->hero_background,
            'hero_media' => $this->hero_media,
            'agents_title' => $this->agents_title,
            'agents_subtitle' => $this->agents_subtitle,
            'cases_title' => $this->cases_title,
            'cases_subtitle' => $this->cases_subtitle,
            'process_title' => $this->process_title,
            'process_subtitle' => $this->process_subtitle,
            'blog_title' => $this->blog_title,
            'blog_subtitle' => $this->blog_subtitle,
            'partners_pill' => $this->partners_pill,
            'partners_title' => $this->partners_title,
            'partners_subtitle' => $this->partners_subtitle,
            'partner_variant1_badge' => $this->partner_variant1_badge,
            'partner_variant1_title' => $this->partner_variant1_title,
            'partner_variant1_desc' => $this->partner_variant1_desc,
            'partner_variant1_percent' => $this->partner_variant1_percent,
            'partner_variant1_percent_label' => $this->partner_variant1_percent_label,
            'partner_variant1_amount_label' => $this->partner_variant1_amount_label,
            'partner_variant1_amount_value' => $this->partner_variant1_amount_value,
            'partner_variant1_tags' => $this->partner_variant1_tags,
            'partner_variant2_badge' => $this->partner_variant2_badge,
            'partner_variant2_title' => $this->partner_variant2_title,
            'partner_variant2_desc' => $this->partner_variant2_desc,
            'partner_variant2_percent' => $this->partner_variant2_percent,
            'partner_variant2_percent_label' => $this->partner_variant2_percent_label,
            'partner_variant2_amount_label' => $this->partner_variant2_amount_label,
            'partner_variant2_amount_value' => $this->partner_variant2_amount_value,
            'partner_variant2_tags' => $this->partner_variant2_tags,
            'partner_earn_min_label' => $this->partner_earn_min_label,
            'partner_earn_min_value' => $this->partner_earn_min_value,
            'partner_earn_min_note' => $this->partner_earn_min_note,
            'partner_earn_top_label' => $this->partner_earn_top_label,
            'partner_earn_top_value' => $this->partner_earn_top_value,
            'partner_earn_top_note' => $this->partner_earn_top_note,
            'partner_earn_audit_label' => $this->partner_earn_audit_label,
            'partner_earn_audit_value' => $this->partner_earn_audit_value,
            'partner_earn_audit_note' => $this->partner_earn_audit_note,
            'partner_steps_title' => $this->partner_steps_title,
            'partner_step1_num' => $this->partner_step1_num,
            'partner_step1_title' => $this->partner_step1_title,
            'partner_step1_desc' => $this->partner_step1_desc,
            'partner_step2_num' => $this->partner_step2_num,
            'partner_step2_title' => $this->partner_step2_title,
            'partner_step2_desc' => $this->partner_step2_desc,
            'partner_step3_num' => $this->partner_step3_num,
            'partner_step3_title' => $this->partner_step3_title,
            'partner_step3_desc' => $this->partner_step3_desc,
            'partner_step4_num' => $this->partner_step4_num,
            'partner_step4_title' => $this->partner_step4_title,
            'partner_step4_desc' => $this->partner_step4_desc,
            'partner_why_title' => $this->partner_why_title,
            'partner_why1_title' => $this->partner_why1_title,
            'partner_why1_desc' => $this->partner_why1_desc,
            'partner_why2_title' => $this->partner_why2_title,
            'partner_why2_desc' => $this->partner_why2_desc,
            'partner_why3_title' => $this->partner_why3_title,
            'partner_why3_desc' => $this->partner_why3_desc,
            'partner_why4_title' => $this->partner_why4_title,
            'partner_why4_desc' => $this->partner_why4_desc,
            'partners_cta_label' => $this->partners_cta_label,
            'partners_cta_title' => $this->partners_cta_title,
            'partners_cta_desc' => $this->partners_cta_desc,
            'partners_cta_button' => $this->partners_cta_button,
            'cta_pill' => $this->cta_pill,
            'cta_title' => $this->cta_title,
            'cta_subtitle' => $this->cta_subtitle,
            'cta_button_text' => $this->cta_button_text,
            'cta_button_telegram' => $this->cta_button_telegram,
            'cta_note' => $this->cta_note,
            'contact_form_pill' => $this->contact_form_pill,
            'contact_form_title' => $this->contact_form_title,
            'contact_form_subtitle' => $this->contact_form_subtitle,
            'contact_form_name_label' => $this->contact_form_name_label,
            'contact_form_phone_label' => $this->contact_form_phone_label,
            'contact_form_company_label' => $this->contact_form_company_label,
            'contact_form_submit_text' => $this->contact_form_submit_text,
            'contact_form_success_title' => $this->contact_form_success_title,
            'contact_form_success_message' => $this->contact_form_success_message,
            'contact_form_privacy_note' => $this->contact_form_privacy_note,
            'contact_phone' => $this->contact_phone,
            'contact_email' => $this->contact_email,
            'contact_address' => $this->contact_address,
            'footer_brand_name' => $this->footer_brand_name,
            'footer_brand_desc' => $this->footer_brand_desc,
            'footer_products_title' => $this->footer_products_title,
            'footer_company_title' => $this->footer_company_title,
            'footer_contacts_title' => $this->footer_contacts_title,
            'footer_phone' => $this->footer_phone,
            'footer_email' => $this->footer_email,
            'footer_telegram' => $this->footer_telegram,
            'footer_copyright' => $this->footer_copyright,
            'marquee_items' => $this->marquee_items,
        ]);
    }
}
